import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import SidebarWrapper from "@/app/components/Sidebar/SidebarWrapper";
import { ReactNode } from "react";

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  variable: "--font-inter",
});

const manrope = Manrope({
  subsets: ["latin", "cyrillic"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Schedify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="ru" className="dark">
      <body
        className={`${inter.variable} ${manrope.variable} bg-surface text-on-surface antialiased`}
      >
        <SidebarWrapper />
        <main className="ml-0 min-h-screen md:ml-68">{children}</main>
      </body>
    </html>
  );
}
